cd export
copy click1.ogg menuhit.ogg
copy click1.ogg back-button-click.ogg
copy click1.ogg pause-continue-click.ogg
copy click1.ogg pause-retry-click.ogg
copy click1.ogg pause-back-click.ogg
copy click2.ogg click-short-confirm.ogg
copy click2.ogg click-close.ogg
copy click2.ogg select-expand.ogg
copy click2.ogg select-difficulty.ogg
copy hover1.ogg menuclick.ogg
copy hover2.ogg click-short.ogg
copy hover2.ogg pause-hover.ogg
::copy keypress.ogg key-press-1.ogg
::copy keypress.ogg key-press-2.ogg
::copy keypress.ogg key-press-3.ogg
::copy keypress.ogg key-press-4.ogg
::copy keypress.ogg key-press-5.ogg
copy empty.mp3 applause.mp3
copy empty.mp3 failsound.mp3
copy empty.mp3 pause-loop.mp3
copy empty.ogg back-button-hover.ogg
copy empty.ogg count1s.ogg
copy empty.ogg count2s.ogg
copy empty.ogg count3s.ogg
copy empty.ogg drum-sliderslide.ogg
copy empty.ogg drum-slidertick.ogg
copy empty.ogg drum-sliderwhistle.ogg
copy empty.ogg normal-sliderslide.ogg
copy empty.ogg normal-slidertick.ogg
copy empty.ogg normal-sliderwhistle.ogg
copy empty.ogg readys.ogg
copy empty.ogg sectionfail.ogg
copy empty.ogg sectionpass.ogg
copy empty.ogg soft-sliderslide.ogg
copy empty.ogg soft-slidertick.ogg
copy empty.ogg soft-sliderwhistle.ogg
copy empty.ogg spinnerspin.ogg
del click1.ogg click2.ogg hover1.ogg hover2.ogg keypress.ogg empty.ogg empty.mp3